<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.1.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envoi de candidature',
	'heading' => 'Envoi du nouveau formulaire',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Coché',
		'checkbox_unchecked' => 'Non coché',
		'submitted_from' => 'Formulaire envoyé depuis le site web :%s',
		'submitted_by' => 'Adresse IP du visiteur :%s',
		'too_many_submissions' => 'Trop d\'envois effectués récemment à partir de cette adresse IP',
		'failed_to_send_email' => 'Echec de l\'envoi du courrier électronique',
		'invalid_reCAPTCHA_private_key' => 'Clé privée reCAPTCHA non valide',
		'invalid_reCAPTCHA2_private_key' => 'Clé privée reCAPTCHA 2.0 non valide.',
		'invalid_reCAPTCHA2_server_response' => 'Réponse du serveur à l\'outil reCAPTCHA 2.0 non valide.',
		'invalid_field_type' => 'Type de champ inconnu « %s »',
		'invalid_form_config' => 'Le champ « %s » a une configuration non valide.',
		'unknown_method' => 'Méthode de requête inconnue du serveur'
	),
	'email' => array(
		'from' => 'groupehorizonetude@gmail.com',
		'to' => 'groupehorizonetude@gmail.com'
	),
	'fields' => array(
		'custom_U2279' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nom  (Obligatoire)',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Nom  (Obligatoire) » est obligatoire.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Adresse E-mail (Obligation)',
			'required' => false,
			'errors' => array(
				'format' => 'Le champ « Adresse E-mail (Obligation) » contient une adresse électronique non valide.'
			)
		),
		'custom_U2426' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Pays de résidence (obligatoire)',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Pays de résidence (obligatoire) » est obligatoire.'
			)
		),
		'custom_U2689' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Prénom (Obligatoire)',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Prénom (Obligatoire) » est obligatoire.'
			)
		),
		'custom_U2704' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Pays d\'origine (obligatoire)',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Pays d\'origine (obligatoire) » est obligatoire.'
			)
		),
		'custom_U2728' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Age',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Age » est obligatoire.'
			)
		),
		'custom_U2740' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Niveau d\'étude',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Niveau d\'étude » est obligatoire.'
			)
		),
		'custom_U2752' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Domaine d\'étude',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Domaine d\'étude » est obligatoire.'
			)
		),
		'custom_U2898' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Si oui, veuillez indiquer le niveau et le domaine d\'étude',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Si oui, veuillez indiquer le niveau et le domaine d\'étude » est obligatoire.'
			)
		),
		'custom_U2910' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Si non, dites nous depuis combien de temps? Avez eu une ou des occupations depuis l\'arrêt de votre scolarité, si oui veuillez les indiquer',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « Si non, dites nous depuis combien de temps? Avez eu une ou des occupations depuis l\'arrêt de votre scolarité, si oui veuillez les indiquer » est obligatoire.'
			)
		),
		'custom_U2922' => array(
			'order' => 12,
			'type' => 'checkboxgroup',
			'label' => 'Dans quelle langue avez vous étudiez?',
			'required' => true,
			'optionItems' => array(
				'Français',
				'Anglais',
				'Espagnol',
				'Arabe',
				'Portugais',
				'Une autre langue'
			),
			'errors' => array(
				'required' => 'Le champ « Dans quelle langue avez vous étudiez? » est obligatoire.',
				'format' => 'Le champ « Dans quelle langue avez vous étudiez? » contient une valeur non valide.'
			)
		),
		'custom_U2837' => array(
			'order' => 9,
			'type' => 'checkboxgroup',
			'label' => 'Etes-vous en étude en ce moment?',
			'required' => true,
			'optionItems' => array(
				'OUI',
				'NON'
			),
			'errors' => array(
				'required' => 'Le champ « Etes-vous en étude en ce moment? » est obligatoire.',
				'format' => 'Le champ « Etes-vous en étude en ce moment? » contient une valeur non valide.'
			)
		)
	)
);

process_form($form);
?>
